#!/usr/bin/perl

$dir=$ARGV[0];

@naloge = `ls $dir`;

for $naloga (@naloge) {
  chomp $naloga;
  system "rm -fr testi/*";
  system "cp $dir/$naloga testi/DN3.java";
  system "cd testi;javac DN3.java";
  system "cd testi;java DN3 1 5 7";
  system "read";
}